### ISSUE TITLE
Notification not working in android release mode

### ISSUE THREAD

**Issue by rmn183** [emekalites/react-native-alarm-notification#100]
In release mode notifications are not coming.

**Comment by natemartins** [comment]
I'm having the same issue. It works well in dev mode but when built for release, it doesn't. @emekalites Kindly look into this.

**Comment by natemartins** [comment]
I've figured this out. You'd have to set `SCHEDULED_EXACT_ALARM` permission in AndroidManifest file. If this does not work, also make sure you set the alar trigger early in your app; probably in `index` or `app` file.
