### ISSUE TITLE
OnNotificationOpened not work in APP KILLED

### ISSUE THREAD

**Issue by nguyenxuankiet262** [emekalites/react-native-alarm-notification#103]
It works on foreground and background but not work in app killed

**Comment by varunsdcet** [comment]
@nguyenxuankiet262  have you get workaround for this

**Comment by vishva-shukla** [comment]
Have you found any solution?

**Comment by ODINA101** [comment]
same

**Comment by eggn** [comment]
do you have any workaround for this @nguyenxuankiet262 ?

**Comment by gabrielmoncea** [comment]
This issue shouldn't be closed because it's still a problem

**Comment by Shikhar15606** [comment]
@emekalites can you please suggest some workaround for this
