### ISSUE TITLE
How to manually set the alarmId?

### ISSUE THREAD

**Issue by zaarheed** [emekalites/react-native-alarm-notification#106]
When using `scheduleAlarm()` is it possible to provide an `alarmId`? I am setting multiple alarms using a for-loop and they are all getting the same `alarmId` which prevents the notifications from ever firing.

Looking at the `scheduleAlarm()` method [here](https://github.com/emekalites/react-native-alarm-notification/blob/master/android/src/main/java/com/emekalites/react/alarm/notification/ANModule.java), it seems the `alarmId` is calculated from the timestamp and cannot be overridden.

Is there any way around this, or a suggested way to schedule multiple alarms (eg. 300)?

**Comment by lashansamwork** [comment]
facing the same issue, did you find a solution @zaarheed ?

**Comment by zaarheed** [comment]
@lashansamwork i found where to apply the fix for Android, but was on a tight deadline and didn’t have the time to find the equivalent for iOS, test and create a PR. I also haven’t ever done any Java/Kotlin/Swift dev before

If I get time later I might circle back and see if I can put a fix in

**Comment by FurkanOzcelik** [comment]
hi how did you fix it for android, i have tried to add id prop to details in module's index.js and then took it with bundle in ANModule, i tried to set 2 alarms with id: 1 and id: 2 as int, but now alarms are inconsistent they were supposed to repeat with 2 minutes interval and there are 1 minute between them but mostly they ring at same time, before that i had delays of seconds maybe but never alarms were 1 min late
