### ISSUE TITLE
Disable vibrate not work if enable sound

### ISSUE THREAD

**Issue by nguyenxuankiet262** [emekalites/react-native-alarm-notification#107]
Alarm still vibrates if sound is enabled. This is my alarm
const alarm = {
  title: 'Alarm',
  message: 'Tap to open app',
  vibrate: true,
  play_sound: false,
  schedule_type: 'once',
  channel: 'wakeup',
  data: {content: 'my notification id is 22'},
  loop_sound: true,
  has_button: false,
  small_icon: 'logo',
};

**Comment by mukosoft** [comment]
Same problem here. If loop_sound is false, than it works.
