### ISSUE TITLE
Error: duplicate alarm set at date

### ISSUE THREAD

**Issue by rajaroni** [emekalites/react-native-alarm-notification#113]
Hi. I'm trying to set two alarms in the same day. But it is giving me this error . How to add multiple alarms for the same day?

**Comment by Muhammad-Wasi** [comment]
Hey @rajaroni , you can add two alarm in same days but not in same time, you can add many alarm in a same day but needs to set different time, atleast 1 minute difference between two alarm in same day.
Thank you
