### ISSUE TITLE
Multiple Alarms

### ISSUE THREAD

**Issue by Mushi42** [emekalites/react-native-alarm-notification#117]
Hi @emekalites, first Thanks for this package , i got the best one till yet,
I am trying to set multiple alarms but all of the alarms got dismissed on time without any notification. but the last alarm work fine and popping notification.
Not understanding the reason.
anyone please help?

**Comment by Mushi42** [comment]
For Android i got a workaround by changing the logic for alarmId. The issue was with the alarmId in Android/app/sec/main/AlarmUtil.java file you can configure with your own logic to make it unique on every single try.👍
It worked for me Thanks

**Comment by vishva-shukla** [comment]
Hi @Mushi42, What changes you have made? I'm also facing the same problem

**Comment by Mushi42** [comment]
> Hi @Mushi42, What changes you have made? I'm also facing the same problem 

Hi @vishva-shukla , in alarmUtil.java (also complete file path mentioned above) there we have logic to generate unique id for every individual alarm but somehow the built in logic was not working for me . So i take current time in unix and make it the id for alarm. Which will be unique for every ms. That's how it's working for me.

Thanks
