### ISSUE TITLE
How to fire a function when notification is Clicked.

### ISSUE THREAD

**Issue by rautram** [emekalites/react-native-alarm-notification#12]
Thanks for this library. From the docs I can't figure out how to fire a function to snooze or stop the notification when notification is clicked.

**Comment by emekalites** [comment]
not available at the moment but we could add that soon

**Comment by LDty** [comment]
Thanks a lot

**Comment by claude39** [comment]
Any update on this issue? I also would like to do what @rautram specifies :(

**Comment by emekalites** [comment]
Feature has been added to version 1.3.1
