### ISSUE TITLE
[iOS Alarm] Can you take a look and create alarm on ios?

### ISSUE THREAD

**Issue by ducpt2** [emekalites/react-native-alarm-notification#13]
Please take a look at this library: https://github.com/smartliang/react-native-alarm.
It work on android and ios, but seem like we can not clear the alarm.
Maybe it will give you the way to implement on iOS.

Love your work.

**Comment by emekalites** [comment]
Thanks @ducpt2, I'll take a look at the library and implement the iOS.

**Comment by 532815096** [comment]
@ducpt2 react-native-alarm   just need add this code 
![image](https://user-images.githubusercontent.com/12792386/47060036-6919d880-d1fe-11e8-9f86-755c2c4496ab.png)

**Comment by emekalites** [comment]
@haifahrul i havent done either. is it something you could do? It'll take me a while before i can make some changes on this plugin

**Comment by codemeall** [comment]
@emekalites any update on implementing the same in IOS ?

**Comment by emekalites** [comment]
@codemeall currently working on it

**Comment by codemeall** [comment]
To get star on IOS, should I have to do any additional tweaks or just linking the package is enough?

Please let me know

**Comment by emekalites** [comment]
Well, that all depends but i think just linking the package will be enough.

**Comment by codemeall** [comment]
@emekalites its not working with IOS, I tried linking too :(

**Comment by emekalites** [comment]
@codemeall I'm not done yet, thats why the label "ongoing" is attached to this issue

**Comment by haifahrul** [comment]
@codemeall Did you trying this [Link](https://github.com/emekalites/react-native-alarm-notification/issues/13#issuecomment-430475856)

**Comment by emekalites** [comment]
@haifahrul yes I did, it helped. Still working on it though. Problem is having to share my 24 hours to do my work and support this plugin as well.

**Comment by kaanoner3** [comment]
Any update ? can we use this plugin on ios ?

**Comment by emekalites** [comment]
not yet @kaanoner3 , there is a lockdown in my country so i'm currently working on it.

**Comment by usama23sep** [comment]
Hi, when can we expect an update?

**Comment by emekalites** [comment]
yes @usama23sep

**Comment by emekalites** [comment]
iOS update currently in progress. checkout the latest version.

**Comment by emekalites** [comment]
Alarm works on iOS on the current version.

**Comment by Vishal7591** [comment]
@emekalites, NSInvalidArgumentException error 0 while execution of the function scheduleAlarm() in iOS

**Comment by emekalites** [comment]
I think it's safe to close this since iOS has been added in v1.7.0.
Thank you all for making this possible.

**Comment by headit74** [comment]
Hey, @emekalites 
It has still the same exception, ```The operation couldn't be completed. (NSInvalidArgumentException error 0.)```

**Comment by hazelf42** [comment]
Just want to pop in and say I'm getting the error as well.

**Comment by TopeMateo** [comment]
Hi, this error happened to me when I'm scheduling a repeating alarm with no "loop_sound" props on the alarm data.
