### ISSUE TITLE
Not receiving notification in Android 8.0 (Oreo)

### ISSUE THREAD

**Issue by sreeharim** [emekalites/react-native-alarm-notification#14]
In android 8.0 version, I am only getting alarm sound. Not receiving any notification. Works fine in other android versions.

**Comment by haifahrul** [comment]
> In android 8.0 version, I am only getting alarm sound. Not receiving any notification. Works fine in other android versions.

[Related Issue](https://github.com/emekalites/react-native-alarm-notification/issues/18#issuecomment-466809009)

**Comment by aniksharif** [comment]
Any update @emekalites ? I am facing this problem too

**Comment by akinmac002** [comment]
Problem resolved on https://github.com/emekalites/react-native-alarm-notification/issues/36#issuecomment-545886812

**Comment by emekalites** [comment]
this has been solved in the latest version
