### ISSUE TITLE
How to use 'react-native-alarm-notification'...

### ISSUE THREAD

**Issue by bajrangsharma-burrp** [emekalites/react-native-alarm-notification#15]
Hi,

**Plz provide a demo app to implement 'react-native-alarm-notification' and fire notification even when app is closed means inactive.**

**How to use 'react-native-alarm-notification' to wakeup the app periodically????**...

**Comment by bajrangsharma-burrp** [comment]
Any hope for the same implementation logic...

**Comment by emekalites** [comment]
yes i'll try to look into this by weekend. I am very occupied with a lot of work

**Comment by emekalites** [comment]
https://github.com/emekalites/react-native-alarm-notification/tree/master/example
