### ISSUE TITLE
OnNotificationOpened not working in quit state / app killed

### ISSUE THREAD

**Issue by ihsan2** [emekalites/react-native-alarm-notification#153]
I click the notification when app killed or quit state but Event OnNotificationOpened not working. In foregorund & background is fine. Thank you

**Comment by komailabbas12** [comment]
> I click the notification when app killed or quit state but Event OnNotificationOpened not working. In foregorund & background is fine. Thank you

Did you solve this?? i am facing the same issue

**Comment by salman521** [comment]
Still facing this issue.
