### ISSUE TITLE
Build Failing after integration

### ISSUE THREAD

**Issue by ananthsridhar** [emekalites/react-native-alarm-notification#17]
Post following steps and adding to project, build is failing with below error
![image](https://user-images.githubusercontent.com/10885810/47374553-dc927d00-d70b-11e8-94c5-33e229563a83.png)

Tried changing the target sdk compile sdk, all above 26, etc, but still getting same error. Any suggestions?

**Comment by baxinJoker** [comment]
I get the same error, how to fix it

**Comment by emekalites** [comment]
I suggest you try opening the android folder of your project in android studio so that android studio can do a build and help you figure out what the real issue is. moreover, a new version is on npm now, you could try that one too.
Thanks.
