### ISSUE TITLE
Missing notification dismiss?

### ISSUE THREAD

**Issue by tsanio** [emekalites/react-native-alarm-notification#20]
I was looking for a way to run something when user dismisses the notification, but I couldn't find one?
Is there some way to do that or is this going to be added at some point?
Here is some [related discussion](https://stackoverflow.com/questions/14671453/catch-on-swipe-to-dismiss-event)

**Comment by emekalites** [comment]
Hi, I think this might be something I'll consider at some point. Maybe you could add it to your code and submit a pull request. That will be lovely.

**Comment by tsanio** [comment]
Hey! Great. Sure. I will have a look at it.

**Comment by emekalites** [comment]
Hey @tsanio, just merged your code, but i wanted to know if there is a need to update the readme file.

**Comment by tsanio** [comment]
Hey, that's awesome! I forgot about editing the readme. If add something like commented in the [pull request](https://github.com/emekalites/react-native-alarm-notification/pull/23) into the readme, it might help users.

**Comment by emekalites** [comment]
Okay thats fine, I'll add it and release a new version. Thanks

**Comment by emekalites** [comment]
Its working in version 1.3.1, thanks for your contribution.
