### ISSUE TITLE
Add multiple alarms

### ISSUE THREAD

**Issue by fauzynurn** [emekalites/react-native-alarm-notification#21]
Hey i've just started using this library and this worked nicely!

but there was a problem when i tried to add three alarms. It just took the last alarm i made ( the third alarm ). How can i fix it? Thanks.

**Comment by fauzynurn** [comment]
Yes. I forgot to change the ids. stupid me. thanks!

**Comment by DanyalAslam** [comment]
> Did you try using different id's?

Where Should I give Id's ?
