### ISSUE TITLE
App does not open after its closed and there is no alarm triggered on the scheduled time

### ISSUE THREAD

**Issue by kunal886496** [emekalites/react-native-alarm-notification#22]
The app does not opens when on the scheduled time and i cant hear the alarm also

**Comment by emekalites** [comment]
I think you should check your phone, i doubt is has to do with the plugin. Moreover you could try the example folder and the new version, then let me know if it worked.

**Comment by haifahrul** [comment]
> The app does not opens when on the scheduled time and i cant hear the alarm also


@kunal886496 Maybe wrong configuration in yout code. I have tried, and the scheduled time it's work in Android 7.1.1, not in Android 8.0 above

**Comment by VikasTiwari7** [comment]
same issue exist into the oneplus and samsung devices
