### ISSUE TITLE
ReactNativeAN.deleteAlarm is not working

### ISSUE THREAD

**Issue by cocoafuel** [emekalites/react-native-alarm-notification#25]
I have linked everything properly and defined the future alarm with and ID but when i try to delete the alarm , it does nothing. I have tried giving string and integers and even hard coded values for id but still nothing happens.

**Comment by emekalites** [comment]
hi @cocoafuel sorry for the late response. Are you saying the alarm still rings after you have deleted it?

**Comment by muhammad-asad-26** [comment]
Hi @emekalites 
Hope you're doing great. 

We have a list of alarms, the user can delete the alarm or we want to delete some alarms based on the response we get from the server. We have associated an ID with every alarm. We have stored the context/details of all alarms on our server. In order delete some alarm we simply passes the ID to cancelAlarm method but nothing happens. The alarms are still available in the list of alarms that we retrieve from one of your methods to get alarms list.

Can you please help us resolve this issue.

**Comment by emekalites** [comment]
I'll take a look at this today @muhammad-asad-26

**Comment by muhammad-asad-26** [comment]
Hi @emekalites
Did you get a chance to look at it.

**Comment by brunobraz100** [comment]
Hello. Any news about this issue?

**Comment by muhammad-asad-26** [comment]
Hi @brunobraz100 
Unfortunately no update on this one. We ended up writing our own module according to our custom needs.

**Comment by brunobraz100** [comment]
Muhamammad,

Thank you for your answer and your time.

Do you have any example about how we can delete a list of alarms? We have
some schedules that need to be deleted before create new ones.




Em sex, 12 de jul de 2019 às 13:30, Muhammad Asad <notifications@github.com>
escreveu:

**Comment by muhammad-asad-26** [comment]
Those all are proprietary code snippets cannot share with you, but I'll find you some sample from where we also took help and make it working.

**Comment by brunobraz100** [comment]
I really thank you for your help!

Em sex, 12 de jul de 2019 às 13:41, Muhammad Asad <notifications@github.com>
escreveu:

**Comment by muhammad-asad-26** [comment]
https://developer.android.com/training/scheduling/alarms
https://developer.android.com/reference/android/app/AlarmManager
https://www.javatpoint.com/android-alarmmanager

**Comment by npnik4** [comment]
Does anyone know the solution to this problem? It is also happening to me.

**Comment by brunobraz100** [comment]
We did native for IOS and android.

Em qua, 8 de abr de 2020 23:28, npnik4 <notifications@github.com> escreveu:

**Comment by emekalites** [comment]
already tracking this in #29

**Comment by ZiyaDogramaci** [comment]
You can fix this issue by changing the following line on AlarmDatabase.java => getAlarm function

`String selectQuery = "SELECT * FROM " +TABLE_NAME+ " WHERE " + COL_DATA + " LIKE '%" + _id + "%'";`

**Comment by agungsb** [comment]
Any update on this? I'm experiencing the same issue here.. :(

**Comment by Jchiu05** [comment]
> You can fix this issue by changing the following line on AlarmDatabase.java => getAlarm function
> 
> `String selectQuery = "SELECT * FROM " +TABLE_NAME+ " WHERE " + COL_DATA + " LIKE '%" + _id + "%'";`

This didn't fix it for me :/

**Comment by emekalites** [comment]
Can you please give me a few more details about the issue you are having right now @Jchiu05

**Comment by emekalites** [comment]
Let’s follow this issue on
