### ISSUE TITLE
Running the app on background

### ISSUE THREAD

**Issue by jheyjheyjhey** [emekalites/react-native-alarm-notification#26]
Hi, new to react-native and playing around with alarm app. 

I managed to let the alarm capability work. However, I am concern if the app can run as background process.

I tried the following: 

1. Open the app
2. Set up the alarm for 30 seconds later when component is mounted.
3. Click the home button.
4. Remove it to the list of recent apps opened.

Sadly, the alarm isn't triggered when I tried removing it to the list of apps. I am trying to achieve something that will let the alarm capability run on background process, same as with the normal phone alarm clock.

Btw, I was using an android emulator. 

Can I use the app the same way as I described above? Thanks!

**Comment by claude39** [comment]
I solved that one by launching a new intent in the receiver.

**Comment by jheyjheyjhey** [comment]
@claude39 Can you give examples? I'm not really familiar with most stuff and your help is much appreciated.

**Comment by haifahrul** [comment]
Hi, @jheyjheyjhey did you solved this issue? or got some solution?

**Comment by iamabdulhaseeb** [comment]
Did any of you solve this?
