### ISSUE TITLE
how to full screen notification show on lock screen?

### ISSUE THREAD

**Issue by Sarathphd** [emekalites/react-native-alarm-notification#28]

**Comment by emekalites** [comment]
I think this is a feature thats enabled by your device settings.

**Comment by Sarathphd** [comment]
public void onNewIntent(Intent intent) {
try {
Bundle bundle = intent.getExtras();
JSONObject data = BundleJSONConverter.convertToJSON(bundle);
getReactInstanceManager().getCurrentReactContext().getJSModule(
DeviceEventManagerModule.RCTDeviceEventEmitter.class).emit(
"OnNotificationOpened", data.toString());
} catch (Exception e){
System.err.println("Exception when handling notification openned. " + e);
}
}

how to intent heigth and width for notification full screen view

**Comment by Sarathphd** [comment]
public void onNewIntent(Intent intent) {
try {
Bundle bundle = intent.getExtras();
JSONObject data = BundleJSONConverter.convertToJSON(bundle);
getReactInstanceManager().getCurrentReactContext().getJSModule(
DeviceEventManagerModule.RCTDeviceEventEmitter.class).emit(
"OnNotificationOpened", data.toString());
} catch (Exception e){
System.err.println("Exception when handling notification openned. " + e);
}
}


How to set width and height intent for a full scren

**Comment by emekalites** [comment]
are you asking for a full screen notitication?

**Comment by Balasnest** [comment]
@Sarathphd Hey did you manage to get it works? Could please let us know the implementation.

**Comment by Raja0sama** [comment]
> @Sarathphd Hey did you manage to get it works? Could please let us know the implementation.

I was able to resolve this by firebase messaging, on notification receive I was able to open my android app, [Here is the how i did it](https://medium.com/@SuperSami/react-native-full-screen-notification-tricking-android-1761e4fd2ac3)

**Comment by Raserad** [comment]
> > @Sarathphd Hey did you manage to get it works? Could please let us know the implementation.
> 
> I was able to resolve this by firebase messaging, on notification receive I was able to open my android app, [Here is the how i did it](https://medium.com/@SuperSami/react-native-full-screen-notification-tricking-android-1761e4fd2ac3)

Have you released it for ios? Is it possible?

**Comment by Raja0sama** [comment]
> > > @Sarathphd Hey did you manage to get it works? Could please let us know the implementation.
> > 
> > 
> > I was able to resolve this by firebase messaging, on notification receive I was able to open my android app, [Here is the how i did it](https://medium.com/@SuperSami/react-native-full-screen-notification-tricking-android-1761e4fd2ac3)
> 
> Have you released it for ios? Is it possible?

I will be working on it soon, I am sure i will find a way.
