### ISSUE TITLE
Cannot manually remove alarm if the id would parse as a 64bit integer

### ISSUE THREAD

**Issue by bsdunx** [emekalites/react-native-alarm-notification#29]
I was trying to use Date.now().toString() as alarm id and when attempting to manually remove an alarm it would have a parse error in the java module.

**Comment by emekalites** [comment]
I pushed a new version, try it and let me if it works for you. Thanks.

**Comment by npnik4** [comment]
Hi I can't delete alarm, after set.
ReactNativeAN.deleteAlarm('12345'); // trying to delete the alarm

const list = await ReactNativeAN.getScheduledAlarms(); 
^ This returns a list of alarms all with the same id, and marked active, so if i try to set another alarm, after dismissed the first one, it never goes off.

I was able to inspect some of the code in AlarmUtil.java
AlarmModel alarm = getAlarmDB().getAlarm(Integer.parseInt(id)); 
// ^ this returns null in doCancelAlarm(String id)

I don’t t know enough about Android to fix this.
Can you take a look whenever you get a chance.

**Comment by emekalites** [comment]
Yes I will, thanks

**Comment by yikkok-yong** [comment]
Probably can refer to my [reply](https://github.com/emekalites/react-native-alarm-notification/issues/60#issuecomment-653707635).

**Comment by emekalites** [comment]
alarm ids are set and returned starting from v1.5.0. you would not have to set the alarm yourself.
