### ISSUE TITLE
null is object ReactNativeAN.scheduleAlarm

### ISSUE THREAD

**Issue by minh-dai** [emekalites/react-native-alarm-notification#31]

**Comment by AliUZAR** [comment]
+1

**Comment by sumukhah** [comment]
Any updates on the issue?
I am getting same error,

**Comment by minh-dai** [comment]
> Any updates on the issue?
> I am getting same error,

try https://github.com/zo0r/react-native-push-notification

**Comment by emekalites** [comment]
I pushed a new version, try it and let me if it works for you. Thanks.

**Comment by sdakansu** [comment]
I am getting same error. How can I fix it?
