### ISSUE TITLE
Not Working even example

### ISSUE THREAD

**Issue by Tilenozz** [emekalites/react-native-alarm-notification#39]
Good morning,
actually i copyed your example App.js  Emulator built it correctly , but when i set a value in input text (example 120 in future time from now ) , or by pressing Sending Notification Now,, always return an error :

null is not an object ( evaluating 'RNAAlarmNotification.scheduleAlarm'

This by working with EXPO.

In normal way , return this (pressing Send notification Now):

![Cattura](https://user-images.githubusercontent.com/54805850/64237812-69e25880-cefd-11e9-97ef-fb9324220890.PNG)

Can you explain me what i m doing wrong ?

Tyvm

**Comment by emekalites** [comment]
This plugin does not support expo.
Thanks for trying it out.
