### ISSUE TITLE
Geting Error during build

### ISSUE THREAD

**Issue by ranjande** [emekalites/react-native-alarm-notification#4]
Error:Execution failed for task ':react-native-alarm-notification:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by emekalites** [comment]
If you have Android studio, try opening the android code. Android studio should be able to discover what the problem is so you could solve it before compiling again through react-native.

**Comment by emekalites** [comment]
I think the problem has to do with the fact that you are using a more recent version of react-native which has removed override of createJSModules. So i'll update the plugin to support the versions of rn that doesn't require @override.

**Comment by ranjande** [comment]
Dear emekalite. Sorry for late reply. This is much help in case you update the plugin. Please let me know when you update the same. I will retry again and try to implement it to my program. thanks once again for your response.
regards,

**Comment by emekalites** [comment]
@ranjande  you can lookup v1.0.9
