### ISSUE TITLE
Android error new version 1.4.0

### ISSUE THREAD

**Issue by mezalejandro** [emekalites/react-native-alarm-notification#46]
When I installed new version on android studio I have the error:
Unsupported Modules Detected: Compilation is not supported for following modules: android-react-native-alarm-notification, react-native-alarm-notification. Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project.

**Comment by emekalites** [comment]
what version of react native are you using?

**Comment by mezalejandro** [comment]
0.61.5

**Comment by emekalites** [comment]
Yes it.

**Comment by mezalejandro** [comment]
because I am testing and with this:
DeviceEventEmitter.addListener('OnNotificationOpened', async function(e) {
it doesn't work for me, when app is closed

**Comment by emekalites** [comment]
did you update your MainActivity.java with this?. Also, check the Readme to be sure you added all the necessary updates especially in you AndroidManifest.xml

```
...
import android.content.Intent;
import android.os.Bundle;

import com.emekalites.react.alarm.notification.BundleJSONConverter;
import com.facebook.react.ReactActivity;
import com.facebook.react.modules.core.DeviceEventManagerModule;

import org.json.JSONObject;
...

public class MainActivity extends ReactActivity {
    ...

    @Override
    public void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        try {
            Bundle bundle = intent.getExtras();
            if (bundle != null) {
                JSONObject data = BundleJSONConverter.convertToJSON(bundle);
                getReactInstanceManager().getCurrentReactContext().getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class).emit("OnNotificationOpened", data.toString());
            }
        } catch (Exception e) {
            System.err.println("Exception when handling notification opened. " + e);
        }
    }

}
```

**Comment by emekalites** [comment]
You can clone the example folder and try it, i tested it and it works

**Comment by mezalejandro** [comment]
if I have it added, I can check the event when the app is open or in the background

**Comment by emekalites** [comment]
yes
