### ISSUE TITLE
incompatible types: int cannot be converted to String - ANModule

### ISSUE THREAD

**Issue by Lolinpiko** [emekalites/react-native-alarm-notification#48]
I got this error while building with 1.4.3:

```
node_modules/react-native-alarm-notification/android/src/main/java/com/emekalites/react/alarm/notification/ANModule.java:83: error: incompatible types: int cannot be converted to String
            int alarmId = Integer.parseInt(bundle.getInt("alarm_id"));

/node_modules/react-native-alarm-notification/android/src/main/java/com/emekalites/react/alarm/notification/ANModule.java:171: error: incompatible types: int cannot be converted to String
            int alarmId = Integer.parseInt(bundle.getInt("alarm_id"));
```

**Comment by Nirav1432** [comment]
> I got this error while building with 1.4.3:
> 
> ```
> node_modules/react-native-alarm-notification/android/src/main/java/com/emekalites/react/alarm/notification/ANModule.java:83: error: incompatible types: int cannot be converted to String
>             int alarmId = Integer.parseInt(bundle.getInt("alarm_id"));
> 
> /node_modules/react-native-alarm-notification/android/src/main/java/com/emekalites/react/alarm/notification/ANModule.java:171: error: incompatible types: int cannot be converted to String
>             int alarmId = Integer.parseInt(bundle.getInt("alarm_id"));
> ```

Please Write "getString(key:"alarm_id")" instead of getInt, it will solve

**Comment by emekalites** [comment]
I have already pushed a commit to that effect yesterday. I want to test another bug before creating a new version. I'll get the new version out today.
