### ISSUE TITLE
Run Services on, After App Killed

### ISSUE THREAD

**Issue by Nirav1432** [emekalites/react-native-alarm-notification#49]
Is there any way to Invoked scheduled alaram if App is Killed

**Comment by emekalites** [comment]
Alarms are scheduled in alarm managers. An AlarmManager is used to trigger some code at a specific time. It uses the Android SDK's alarm service and runs independently of the application's lifecycle. So even if the app is killed, it can get triggered at the specific time it was set to trigger.

**Comment by Nirav1432** [comment]
> Alarms are scheduled in alarm managers. An AlarmManager is used to trigger some code at a specific time. It uses the Android SDK's alarm service and runs independently of the application's lifecycle. So even if the app is killed, it can get triggered at the specific time it was set to trigger.

Ok Thanks Sir, for your reply
