### ISSUE TITLE
Doesn't work on Android 9

### ISSUE THREAD

**Issue by mattveraldi** [emekalites/react-native-alarm-notification#51]
Hi,
I'm using your library since v1.3.1 version.
It didn't work on Android 9 so I forked your repo and updated the code as written on the [android developer docs](https://developer.android.com/training/notify-user/build-notification) on my [android-o-fix](https://github.com/mattveraldi/react-native-alarm-notification/tree/android-o-fix) branch.

Today I saw that recently you updated your repo to a newer version, so i gave it a try, but still it doesn't work on Android 9.
I looked at the code and noticed that has changed a lot. You did a great job!!

I Hope you can fix it as soon as possible, until then, i'll still use my branch.
Best regards.

**Comment by emekalites** [comment]
Hi could you please let me now why and what changes i can make to get it to work for you because that might help someone.

**Comment by tarunteckedge** [comment]
@emekalites I think he meant with this - https://github.com/mattveraldi/react-native-alarm-notification/commit/9cc4e4ad2dd23e483a94a9118e58037ebbdd9f17

**Comment by emekalites** [comment]
I think i have already implemented for android 9.

**Comment by DanyalAslam** [comment]
How Can I stop Alarm ?

**Comment by emekalites** [comment]
const alarmNotifData = {};

    //Schedule Future Alarm
    const alarm = await ReactNativeAN.scheduleAlarm(alarmNotifData);
    console.log(alarm); // { id: 1 }

    //Delete Scheduled Alarm
    ReactNativeAN.deleteAlarm(alarm.id);


@DanyalAslam
