### ISSUE TITLE
Remove or modify notification actions buttons

### ISSUE THREAD

**Issue by lklima** [emekalites/react-native-alarm-notification#54]
First congratulations on the excellent work, it would be interesting to remove or modify the action buttons of the notification. I use this lib to notify a new delivery.

**Comment by akinmac002** [comment]
I have the same problem.

**Comment by ZiyaDogramaci** [comment]
You can remoe buttons by commenting out the following lines on the file AlarmUtil.java => sendNotification

`            Intent dismissIntent = new Intent(mContext, AlarmReceiver.class);
            dismissIntent.setAction(NOTIFICATION_ACTION_DISMISS);
            dismissIntent.putExtra("AlarmId", alarm.getId());
            PendingIntent pendingDismiss = PendingIntent.getBroadcast(mContext, notificationID, dismissIntent, PendingIntent.FLAG_UPDATE_CURRENT);
            NotificationCompat.Action dismissAction = new NotificationCompat.Action(android.R.drawable.ic_lock_idle_alarm, "DISMISS", pendingDismiss);
            mBuilder.addAction(dismissAction);

            Intent snoozeIntent = new Intent(mContext, AlarmReceiver.class);
            snoozeIntent.setAction(NOTIFICATION_ACTION_SNOOZE);
            snoozeIntent.putExtra("SnoozeAlarmId", alarm.getId());
            PendingIntent pendingSnooze = PendingIntent.getBroadcast(mContext, notificationID, snoozeIntent, PendingIntent.FLAG_UPDATE_CURRENT);
            NotificationCompat.Action snoozeAction = new NotificationCompat.Action(R.drawable.ic_snooze, "SNOOZE", pendingSnooze);
            mBuilder.addAction(snoozeAction);`

**Comment by emekalites** [comment]
The buttons will be hidden by default. But if you need them you can pass "has_button: true"

**Comment by MrTuyennn** [comment]
> The buttons will be hidden by default. But if you need them you can pass "has_button: true"

it's not working

**Comment by MrTuyennn** [comment]
> The buttons will be hidden by default. But if you need them you can pass "has_button: true"

      title: 'my title',
      message: 'my message,
      schedule_type: 'repeat',
      repeat_interval: 'daily,
      auto_cancel: true,
      has_button: true,
=> has_button is not working
- help me ^^. tks <3
