### ISSUE TITLE
If media volume was turned off, the alarm have no sound. 

### ISSUE THREAD

**Issue by hoangan** [emekalites/react-native-alarm-notification#57]
Hi,

As stated in the title. If media volume was turned off, the alarm have no sound. The alarm should raise the media volume when it's firing off. 

Nice work by the way.

Thank you

**Comment by emekalites** [comment]
Thanks but i dont think its necessary, anyone who turns down his/her volume has a reason for that.

**Comment by hoangan** [comment]
Not really, sometimes I accidentally turn off media volume while surfing facebook. For this very reason I discovered the problem above.
