### ISSUE TITLE
When schedule_type is "repeated", stopAlarm snoozes the alarm instead of stopping it

### ISSUE THREAD

**Issue by PhuocHoangMinhNguyen** [emekalites/react-native-alarm-notification#59]
When schedule_type is "repeated", stopAlarm seems to just snooze the alarm instead of stopping it (since the alarm is started just 45 seconds to 1 minute later).

If I'm using schedule_type as "repeat", how should I stop the alarm so that the alarm will start after "repeat_interval" amount of time? Thank you

**Comment by PhuocHoangMinhNguyen** [comment]
Haven't found the solution for this

**Comment by emekalites** [comment]
@PhuocHoangMinhNguyen I just figured it wasn't added earlier. It's going to be available in the next version. v1.5.3.
Thanks for pointing that out.
