### ISSUE TITLE
ReactNativeAN.deleteAlarm() Not working

### ISSUE THREAD

**Issue by Jchiu05** [emekalites/react-native-alarm-notification#60]
I have an alarm scheduled with an alarm id of 1945 for instance, and when I try to delete it by doing 
ReactNativeAN.deleteAlarm("1945"), it doesn't get deleted. I also tried doing ReactNativeAN.deleteAlarm(1945) and ReactNativeAN.deleteAlarm('1945').

For the ReactNativeAN.deleteAlarm(1945) "java.lang.Double cannot be cast to java.lang.String"

None of the examples above works. If you have time, could you please fix this?

**Comment by Jchiu05** [comment]
I think I found the issue? If for instance, I set an alarm with alarm_id = "1", I'm able to delete it.

But it doesn't work for anything  above a certain threshold?

**Comment by Jchiu05** [comment]
I was looking through: https://github.com/emekalites/react-native-alarm-notification/blob/584f1f98ae7d6b29c4fc7af32e8e45666a0b9eff/android/src/main/java/com/emekalites/react/alarm/notification/ANModule.java

and was wondering why you convert string to string twice?
@ReactMethod
    public void deleteAlarm(String alarmID) {
        alarmUtil.doCancelAlarm(alarmID.toString());
    }

**Comment by emekalites** [comment]
Please give me some time to analyse this

**Comment by PhuocHoangMinhNguyen** [comment]
experiencing the same problem

**Comment by PhuocHoangMinhNguyen** [comment]
Does the alarm_id suppose to be Number Type? Because I found:
@ReactMethod
    public void removeFiredNotification(String alarm_id) {
        alarmUtil.removeFiredNotification(Integer.parseInt(alarm_id));
    }
in https://github.com/emekalites/react-native-alarm-notification/blob/584f1f98ae7d6b29c4fc7af32e8e45666a0b9eff/android/src/main/java/com/emekalites/react/alarm/notification/ANModule.java

**Comment by PhuocHoangMinhNguyen** [comment]
When I use the viewAlarms() function I noticed there are 2 types of id: "id" and "alarmId"."alarmId" matches "alarm_id" while "id" doesn't.

This is my theory: The deleteAlarm() function seems to delete the alarm bases on the "id", instead of "alarm_id". So if the "alarm_id" somehow matches "id", it will be deleted successfully. However, if they don't match, then it won't be deleted.

Hope that helps. @Jchiu05 Can you please try to see if my theory is correct in your case?

https://github.com/emekalites/react-native-alarm-notification/blob/master/android/src/main/java/com/emekalites/react/alarm/notification/ANModule.java

**Comment by yikkok-yong** [comment]
Found out the if 

`deleteAlarm(id)` is working. While `deleteAlarm(alarmId)` isn't working. Should update the documentation ?

**Comment by PhuocHoangMinhNguyen** [comment]
@yikkok-yong thank you, that confirms my theory.

**Comment by HarshitMadhav** [comment]
But everytime when we create a new alarm using scheduleAlarm a new alarm is created with the next id (not alarm id) +1 then the previous one irrespective of that alarm is deleted or not.

**Comment by HarshitMadhav** [comment]
Moreover it says that you have already set this alarm no matter how much I delete alarms.

**Comment by PhuocHoangMinhNguyen** [comment]
> Moreover it says that you have already set this alarm no matter how much I delete alarms.

The code actually set the alarm as Inactive instead of actually deleting it. Thats why even though you deleted it, it is still in the AlarmDatabase in the background. I figured it out when reading the code.

**Comment by HarshitMadhav** [comment]
Hi Thanks for replying! So I have created more then 100 alarms in my use case and I have deleted all of them but you mean do they still exists in AlarmDatabase? If yes how to delete them permanently.

**Comment by PhuocHoangMinhNguyen** [comment]
To be honest, I dont know. I had to implement bunch of code to find a work around for that. I cannot share the code but basically I use Math.Random for the alarmID so the alarmID wont be duplicated

**Comment by PhuocHoangMinhNguyen** [comment]
And i think if you delete the app from your device and install it again, the AlarmDatabase will be reset

**Comment by HarshitMadhav** [comment]
Thanks for the idea! I currently require a single scheduled alarm to be created and that can be repeated only for some time duration just a single alarm repeatable many times.

**Comment by HarshitMadhav** [comment]
Ok I will try reinstalling but everytime now I am getting alarm already set I think the buffer is full for AlarmDatabase lol

**Comment by PhuocHoangMinhNguyen** [comment]
I think you already know this but i will say it, hope it will help:
1. Dont set alarm ID as 0. For some reason, it only accepts alarmID > 0
2. Math.random will randomize a number between 0 and 1. For example, 0.44. So always multiply with a number, e.g. 10, 100, etc.
Hope that helps.

**Comment by HarshitMadhav** [comment]
Tried reinstalling it deletes the alarmDatabase now I am seeing a empty array of alarms.

**Comment by HarshitMadhav** [comment]
I am using this to set alarm now  

```
    var alarmNotifData = {
      alarm_id: "12",
      title: "My Notification Title",
      message: "My Notification Message",
      channel: "my_channel_id",
      small_icon: "ic_launcher",
      fire_date: get_times,
      play_sound: true,
      sound_name: 'alarm.mp3',
      color: 'transparent',
      // You can add any additional data that is important for the notification
      // It will be added to the PendingIntent along with the rest of the bundle.
      // e.g.
      data: { foo: "bar" },
    };

    ReactNativeAN.scheduleAlarm(alarmNotifData);

    ReactNativeAN.sendNotification(alarmNotifData);

```
and I am still getting alarm already set even with different alarm ids where get_times is 

>     var get_times = moment(curr_time, 'HH:mm').add(10,'s').format('DD-MM-YYYY HH:mm:ss')

**Comment by emekalites** [comment]
There is no need to call 
```
ReactNativeAN.scheduleAlarm(alarmNotifData);

ReactNativeAN.sendNotification(alarmNotifData);
``` 
this twice for the same alarm with the same alarm_id,

Rather you could do this 

```
var alarmNotifData = {
      alarm_id: "12",
      title: "My Notification Title",
      message: "My Notification Message",
      channel: "my_channel_id",
      small_icon: "ic_launcher",
      fire_date: get_times,
      play_sound: true,
      sound_name: 'alarm.mp3',
      color: 'transparent',
      // You can add any additional data that is important for the notification
      // It will be added to the PendingIntent along with the rest of the bundle.
      // e.g.
      data: { foo: "bar" },
    };

    ReactNativeAN.scheduleAlarm(alarmNotifData);

    var alarmNotifData2 = {...alarmNotifData, alarm_id: "13"}; // set a new id for the notification

    ReactNativeAN.sendNotification(alarmNotifData2);
```

But technically, `ReactNativeAN.scheduleAlarm` should send a notification when the alarm is triggered.
