### ISSUE TITLE
alarmId vs id

### ISSUE THREAD

**Issue by PhuocHoangMinhNguyen** [emekalites/react-native-alarm-notification#61]
Can you please explain the difference between alarmId and id in your code?
https://github.com/emekalites/react-native-alarm-notification/blob/master/android/src/main/java/com/emekalites/react/alarm/notification/ANModule.java

**Comment by emekalites** [comment]
**alarmId** is used while scheduling the alarm `alarm.setAlarmId((int) System.currentTimeMillis());` while **id** is the unique identifier for the database operations

**Comment by PhuocHoangMinhNguyen** [comment]
@emekalites is there any way to edit the "id" (not "alarmId")

**Comment by emekalites** [comment]
so i am thinking, with all the issues with the id, since the id is a unique identifier, I'll save the alarm in the database and return the id to the user 
```
const alarm = ReactNativeAN.scheduleAlarm(details); 
console.log(alarm); // { id = number }
```
