### ISSUE TITLE
Repeat_interval doesn't work correctly.

### ISSUE THREAD

**Issue by PhuocHoangMinhNguyen** [emekalites/react-native-alarm-notification#62]
When using getScheduleAlarms(), I realized that the "repeat_interval" remains the same regardless of the value I chose. Also it appears as "interval" instead of "repeat_interval" in the updated text.

**Comment by sargamverma** [comment]
Repeat_interval  set time is not set.
alarm schedule after 1 min .
const alarmNotifData = {
      alarm_id: "22",
       title: "Hello",
       schedule_type: "repeat",
       repeat_interval: 10 ,
       message: '',
       vibrate: true,
       play_sound: false,
      // schedule_type: "once",
      // data: { content: "my notification id is 22" },
    }; 
		const { fireDate } = this.state;
    const details  = { ...alarmNotifData, fire_date: fireDate };
   
    ReactNativeAN.scheduleAlarm(details);
  };
