### ISSUE TITLE
Is it possible to fire the alarm even if the app is close?

### ISSUE THREAD

**Issue by ffJPabloFlores** [emekalites/react-native-alarm-notification#7]

**Comment by emekalites** [comment]
yes it is.

**Comment by ffJPabloFlores** [comment]
@emekalites Cool, Could you tell me what do I need to do? 
I set up an alarm but when I close the app completely it does not fire. Do  I need to send a specific parameter o do something else?

The alarm works if the app is open o move in the background

**Comment by emekalites** [comment]
Let me check it again @ffJPabloFlores

**Comment by emekalites** [comment]
@ffJPabloFlores The alarm works even if you kill it, make sure to add these to your AndroidManifest.xml

    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
	<uses-permission android:name="android.permission.VIBRATE"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />

    <application ....>
        <service android:name="com.emekalites.react.alarm.notification.ANService" android:enabled="true"/>
        <receiver android:name="com.emekalites.react.alarm.notification.ANAlarmReceiver" android:enabled="true"/>
        <receiver android:name="com.emekalites.react.alarm.notification.ANBootReceiver" android:enabled="true" android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
                <action android:name="android.intent.action.QUICKBOOT_POWERON"/>
                <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
            </intent-filter>
        </receiver>
     .....

**Comment by kunal886496** [comment]
It does not opens. Please help

**Comment by komailabbas12** [comment]
not working
