### ISSUE TITLE
If the new alarm has the same alarm_id as the deleted alarm, it wont be set.

### ISSUE THREAD

**Issue by PhuocHoangMinhNguyen** [emekalites/react-native-alarm-notification#71]
If the new alarm has the same alarm_id as the deleted alarm, it won't be set. It is because when deleting the alarm, it is set as "inactive" instead of being deleted for real.

**Comment by emekalites** [comment]
I have decided to delete the alarm from the database entirely in the next version update.

**Comment by PhuocHoangMinhNguyen** [comment]
@emekalites completely wonderful, thank you.
