### ISSUE TITLE
Click on Notification?

### ISSUE THREAD

**Issue by PhuocHoangMinhNguyen** [emekalites/react-native-alarm-notification#72]
Is there any way to perform a click on the notification in react-native-alarm-notification?

**Comment by emekalites** [comment]
yes, the code supports it

**Comment by PhuocHoangMinhNguyen** [comment]
@emekalites can you leave some hints?

**Comment by emekalites** [comment]
check the example folder

**Comment by PhuocHoangMinhNguyen** [comment]
Sorry, I reply a bit late. I want to go to a specific screen of the application when clicking on the alarm notification. I do not see that option in the example folder.
