### ISSUE TITLE
Alarm can't triggered when app opened ? this can run on the foreground and background ???

### ISSUE THREAD

**Issue by NaufalAmmar** [emekalites/react-native-alarm-notification#73]
Hello, I wanna ask something about this library, this can run on the foreground and background ???

**Comment by PhuocHoangMinhNguyen** [comment]
I tried using it and it could run no matter I opened it or not. Maybe the problem is in your code.

**Comment by NaufalAmmar** [comment]
@PhuocHoangMinhNguyen can I see your code?

**Comment by PhuocHoangMinhNguyen** [comment]
I won't give you the entire code, which part you need specifically?

**Comment by NaufalAmmar** [comment]
code usage for alarm

**Comment by jknap** [comment]
Hello, I run into the same issue on iOS, the notification is only triggered when the app is in the background.

Here's the snippet I used (inspired from the README):
```
    const fireDate = ReactNativeAN.parseDate(new Date(Date.now() + 10000)); // set the fire date for 10 second from now
    const alarmNotifData = {
      title: 'My Notification Title',
      message: 'My Notification Message'
    };
    await ReactNativeAN.scheduleAlarm({
      ...alarmNotifData,
      fire_date: fireDate
    });
```
Version: 1.6.0

**Comment by Udith-Murali-K** [comment]
Any updates regarding this , need to trigger the notification when the app is even in foreground

**Comment by emekalites** [comment]
Thanks for the feedback, the iOS is still very much under production. It will be fixed in the full release, hopefully the next version.

**Comment by namansukhwani** [comment]
> I won't give you the entire code, which part you need specifically?

Man Can you please send the code for this lib working in background

**Comment by emekalites** [comment]
I think this works well in the current version. Please check v1.7.1 and provide feedback. Thanks

**Comment by beinghussain** [comment]
Does not work when the app is killed. 

React native code: 

`const message = `Time ${endTime ? `for ${replace(name, ' End', '')}` : `left for ${replace(name, ' Start')}`} ${endTime ? 'ends in' : ''}`
        const title = `${name} Namaz`
        const alarmNotifData = {
          title,
          message,
          channel: 'my_channel_id',
          auto_cancel: true,
          schedule_type: 'once',
          small_icon: 'notification',
          data: { timeKey, type: 'alert' },
        }
        // const fireDate = ReactNativeAN.parseDate(alarmTime.toDate()) // set the fire date for 1 second from now
        const fireDate = ReactNativeAN.parseDate(new Date(Date.now() + 5000)) // set the fire date for 1 second from now

        console.log('fireDate', fireDate)
        await ReactNativeAN.scheduleAlarm({ ...alarmNotifData, fire_date: fireDate })
`

Apps Manifest:

`
  <receiver
            android:name="com.emekalites.react.alarm.notification.AlarmReceiver"
            android:enabled="true"
            android:exported="true">
            <intent-filter>
                <action android:name="ACTION_DISMISS" />
                <action android:name="ACTION_SNOOZE" />
            </intent-filter>
        </receiver>


        <receiver
            android:name="com.emekalites.react.alarm.notification.AlarmDismissReceiver"
            android:enabled="true"
            android:exported="true" />

        <receiver
            android:name="com.emekalites.react.alarm.notification.AlarmBootReceiver"
            android:directBootAware="true"
            android:enabled="false"
            android:exported="true"
            tools:targetApi="n">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.QUICKBOOT_POWERON" />
                <action android:name="com.htc.intent.action.QUICKBOOT_POWERON" />
                <action android:name="android.intent.action.LOCKED_BOOT_COMPLETED" />
            </intent-filter>
        </receiver>
`
