### ISSUE TITLE
How to push intent to full screen notification when there was an alarm

### ISSUE THREAD

**Issue by CayBap** [emekalites/react-native-alarm-notification#78]
Please help me,
I don't push full screen notification  and stop alarm

**Comment by emekalites** [comment]
Hi @CayBap , I do not think full screen notification is possible at this time. meanwhile please check the ReadMe to see how you can add a stop button to the notification.

**Comment by CayBap** [comment]
@emekalites , I want to show notification as image when the phone was locked 
[https://imgur.com/0e09HSy](url)

**Comment by CayBap** [comment]
@emekalites  I call function stopAlarmSound() but The vibration still work

**Comment by emekalites** [comment]
@CayBap I'm sorry, It's not possible to show the notification as you represented it in the image. Maybe in the future i'll consider to add fullscreen notifications.

**Comment by emekalites** [comment]
> @emekalites I call function stopAlarmSound() but The vibration still work

#79
