### ISSUE TITLE
Android keeps vibrating forever

### ISSUE THREAD

**Issue by sebastian-sanchez-variv** [emekalites/react-native-alarm-notification#79]
If the vibrate option is set to true, the vibration keeps forever, no matter if the alarm has been silenced (through ReactNativeAN.stopAlarmSound();) or even if it was deleted (through ReactNativeAN.deleteAlarm(id) or even ReactNativeAN.removeAllFiredNotifications())

**I was able to fix it by changing your native code on AlarmUtil.java as follows:**
In the method stopAlarmSound() (lines 510-513) I added following code:

```
Vibrator vibrator = (Vibrator) mContext.getSystemService(Context.VIBRATOR_SERVICE);
        if (vibrator.hasVibrator()) {
            vibrator.cancel();
        }
```

So that now instead of having: 

```
void stopAlarmSound() {
        Log.e(TAG, "stop alarm sound");
        audioInterface.stopPlayer();
    }
```

you have:

```
void stopAlarmSound() {
        Log.e(TAG, "stop alarm sound");
        Vibrator vibrator = (Vibrator) mContext.getSystemService(Context.VIBRATOR_SERVICE);
        if (vibrator.hasVibrator()) {
            vibrator.cancel();
        }
        audioInterface.stopPlayer();
    }
```

Tested on Android 10 & working

**Comment by emekalites** [comment]
Thanks, @sebastian-sanchez-variv I'll update the code in the next version.
