### ISSUE TITLE
Navigate to a specific screen when clicking on the notification

### ISSUE THREAD

**Issue by PhuocHoangMinhNguyen** [emekalites/react-native-alarm-notification#80]
Is there any way to navigate to a specific screen of the application when clicking on the alarm notification?
I do not see that option in the example folder.

**Comment by wanderlust252** [comment]
try OnNotificationOpened in DOCS

**Comment by Tushaarv** [comment]
> try OnNotificationOpened in DOCS

can you suggest how to achieve this and get reference to navigation?
