### ISSUE TITLE
Alarms not Working in ios

### ISSUE THREAD

**Issue by sure61** [emekalites/react-native-alarm-notification#81]
Hi your package working good in android but in ios it giving some problems setAlarm and send notification not working in ios

**Comment by swlaunch** [comment]
There are still many missing parts for iOS like event listeners for Opening and Dismissing alarms.
@emekalites do you have any plan on enhancing iOS part of the module?

**Comment by emekalites** [comment]
@swlaunch, I am almost done with with the iOS updates.

**Comment by emekalites** [comment]
Please check the current for the most updated iOS functionalities.

**Comment by sure61** [comment]
Hi @emekalites  i tried your latest updates to ios. SetAlarm method  is not working when i invoked it gives "failed to create alarm error".

**Comment by emekalites** [comment]
@sure61 it'd have been better if you created a new issue on this. Meanwhile, can you retrieve more information regarding the failed function?
