### ISSUE TITLE
setAlarm  Error..

### ISSUE THREAD

**Issue by HERYORDEJY** [emekalites/react-native-alarm-notification#84]
I am using the example code, whenever I try to set the alarm, I get an error message, ... **[TypeError: null is not an object (evaluating 'RNAlarmNotification.scheduleAlarm')]**

![Screenshot (4)](https://user-images.githubusercontent.com/37557949/93330311-84405900-f816-11ea-95ba-f934edaacb09.png)

**Comment by emekalites** [comment]
I think i have an idea as to where the problem is coming from, I'll push an update soon @HERYORDEJY

**Comment by seba-wetzel** [comment]
HI, this error [TypeError: null is not an object (evaluating 'RNAlarmNotification.scheduleAlarm')] happen when you don't rebuild the app after install the lib.
Has to run npx react-native run-andoid and it will be fixed.
