### ISSUE TITLE
Android error

### ISSUE THREAD

**Issue by mezalejandro** [emekalites/react-native-alarm-notification#88]
Hi how are you doing?
Using sentry I got an alert:
![Screen Shot 2020-09-30 at 01 01 08](https://user-images.githubusercontent.com/568141/94641751-7a0f6780-02b8-11eb-81cd-213f6f037687.png)

![Screen Shot 2020-09-30 at 01 02 02](https://user-images.githubusercontent.com/568141/94641800-9a3f2680-02b8-11eb-99a6-ac3c715f5c1d.png)

Thanks

**Comment by emekalites** [comment]
wow did not anticipate this. I'll see if there is some solution to this.
