### ISSUE TITLE
ISSUE WITH METHODS...

### ISSUE THREAD

**Issue by CastilloLuis** [emekalites/react-native-alarm-notification#9]
Hi!!! This is the first time that i used this module...
I have the configuration bellow, the problem is that when i press the button, the scheduleAlarm and others method does not work...:

The error says:

**Uncaught Error: undefined is not an object (evaluating 'RNALarmNotification.scheduleAlarm')**

I dont know what to do! I also linked and add the part of the xml, and check the .java files. But everything is ok!

Thanks

`    

    setAlarm = () => {
        const fireDate = new Date(Date.now() + 5000);     // set the fire date for 1 second from now
        const alarmNotifData = {
            id: "12345",                                  // Required
            title: "My Notification Title",               // Required
            message: "My Notification Message",           // Required
            ticker: "My Notification Ticker",
            auto_cancel: true,                            // default: true
            vibrate: true,
            vibration: 100,                               // default: 100, no vibration if vibrate: false
            small_icon: "ic_launcher",                    // Required
            large_icon: "ic_launcher",
            play_sound: true,
            sound_name: null,                             // Plays custom notification ringtone if sound_name: null
            color: "red",
            schedule_once: true,                          // Works with ReactNativeAN.scheduleAlarm so alarm fires once
            tag: 'some_tag',
            fire_date: ReactNativeAN.parseDate(fireDate)  // Date for firing alarm, Required for ReactNativeAN.scheduleAlarm. Format: dd-MM-yyyy HH:mm:ss
        };
        ReactNativeAN.scheduleAlarm(alarmNotifData);
    }`

**Comment by CastilloLuis** [comment]
But I use npm install and it throw a error that dont found "parseData" function. So, I have clone the repository, and implemented, and I got the error Uncaught Error: undefined is not an object (evaluating 'RNALarmNotification.scheduleAlarm'). I checked the java files and everything is ok, the same in the npm or readme. What shoul I do? Thank uu!

**Comment by emekalites** [comment]
I've updated the codes with a new release v1.2.0 @CastilloLuis

**Comment by LuisEduardoRibeiro** [comment]
Hi! I have the same issue. How can I resolve?

**Comment by emekalites** [comment]
> How to fire a function when notifications is clicked.

@rautram check new version 1.3.1

**Comment by emekalites** [comment]
> Hi! I have the same issue. How can I resolve?

have you figured out a way yet?

**Comment by Tilenozz** [comment]
same trouble.
Always return error with "null is not an object"

**Comment by ngocht143** [comment]
@emekalites 
hi, I install your lib by 
`yarn add react-native-alarm-notification` then `pod install`
I got exception: null is not an object (evaluating 'RNAlarmNotification.scheduleAlarm'). maybe it's an issue about linking with native modules

**Comment by Akijunior** [comment]
Hello. I'm learning react now and I like make a simple alarm to my app, but I don't understand how to use this library. Can you explain me or make a video explain step to step about how set her in a simple project? 
When I tried follow the documentation I get the error RNAlarmNotification.sendNotification null is not an object since 2 days ago.

**Comment by CoderSudaWuda** [comment]
TypeError: null is not an object (evaluating 'RNAlarmNotification.scheduleAlarm')

I get this error too.
