### ISSUE TITLE
Navigate to a screen using device event emitter

### ISSUE THREAD

**Issue by PhuocHoangMinhNguyen** [emekalites/react-native-alarm-notification#91]
Issue:
I am trying to navigate to another screen after triggering DeviceEventEmitter.addListener('OnNotificationOpened') but it doesn't work.

Version:
React-Native Version: 0.63.3
React-Native-Alarm-Notification: 1.4.6

Code:
DeviceEventEmitter.addListener('OnNotificationOpened', async function (e) {
            const obj = JSON.parse(e);
            this.props.navigation.navigate('Screen Two', obj)
});

Error: 
TypeError: undefined is not an object (evaluating 'this.props')

**Comment by emekalites** [comment]
please try this with the new v1.7.1
