### ISSUE TITLE
NSInvalidArgumentException error 0 while execution of the function scheduleAlarm() in iOS

### ISSUE THREAD

**Issue by ElChawich** [emekalites/react-native-alarm-notification#92]
it was working on iOS and android on a previous version, after i updated to the new version its giving the mentioned error in iOS.

using RN 0.59.9

**Comment by headit74** [comment]
When I try to add an alarm on ios, it shows this error.
`The operation couldn’t be completed. (NSInvalidArgumentException error 0.)`

**Comment by CapiPato** [comment]
im also getting this error on iOS

**Comment by ElChawich** [comment]
@CapiPato did u try adding "loop_data:true" to the alarm data?

**Comment by headit74** [comment]
Yes, didn't help

**Comment by CapiPato** [comment]
> @CapiPato did u try adding "loop_sound:true" to the alarm data?

Yes, and got the same result

**Comment by abhi-amci** [comment]
I am also facing the same issue

**Comment by hazelf42** [comment]
This did fix my issue as well, though I actually do have a need to loop the sound for an alarm, which loop_sound doesn't seem to do.

**Comment by degemenc** [comment]
Even though the documentation says loop_sound is false by default, it was not coded in. Please check out my PR, it should solve this.
