### ISSUE TITLE
[ios] Alarm not being added when in loop, and "tag" not being added to alarm details

### ISSUE THREAD

**Issue by ElChawich** [emekalites/react-native-alarm-notification#96]
I'm working on RN 0.59.5, basically I'm adding 10 alarms using a for loop, and its working perfectly on android. But on iOS, even though its giving success for the 10 alarms, its only adding the last alarm in the loop... 

and another issue on iOS is not giving details for the alarm as much as on android when getScheduledAlarms() function is called, even though I'm giving a tag for the alarm, its not showing it, and its only showing the main info regarding the alarm, which are alarm time and date and its id.

**Comment by rmn183** [comment]
Yes @ElChawich right, when we add multiple sound_names in react-native iOS only and set the alarm time for any time. It only throws the default tone but not the added sound_names, not even the loop is in working mode, but for single sound_name it is going well. I went through the package library of react-native-alarm-notifications and found that there is no such option of sound_names in AppDelegate.m file.
